title:           "Zsolt Jurányi (juzraai)"
description:     "Hi, I'm Zsolt. I develop crawlers and other stuff, check them out! :)"
author:          "Zsolt Jurányi"
baseurl:         ""
url:             "https://juzraai.github.io"

og_image:        "/img/og-image.png"
og_image_type:   "image/png"
og_image_width:  1200
og_image_height: 630

social:
  - url:   "https://github.com/juzraai"
    title: "Check out my GitHub profile!"
    icon:  "icon-gh"
  - url:   "https://facebook.com/juzraai"
    title: "Follow me on Facebook!"
    icon:  "icon-fb"

markdown: kramdown
kramdown:
   input: GFM
   hard_wrap: false